
.. DO NOT EDIT.
.. THIS FILE WAS AUTOMATICALLY GENERATED BY SPHINX-GALLERY.
.. TO MAKE CHANGES, EDIT THE SOURCE PYTHON FILE:
.. "auto_examples\integration_with_error.py"
.. LINE NUMBERS ARE GIVEN BELOW.

.. only:: html

    .. note::
        :class: sphx-glr-download-link-note

        Click :ref:`here <sphx_glr_download_auto_examples_integration_with_error.py>`
        to download the full example code

.. rst-class:: sphx-glr-example-title

.. _sphx_glr_auto_examples_integration_with_error.py:


Check Integration
=================

Makes sure that automatically chosen integral bounds perform similar to or
better than what you would choose by hand.

.. GENERATED FROM PYTHON SOURCE LINES 8-124



.. rst-class:: sphx-glr-horizontal


    *

      .. image:: /auto_examples/images/sphx_glr_integration_with_error_001.png
          :alt: what does a usual error bar look like?
          :class: sphx-glr-multi-img

    *

      .. image:: /auto_examples/images/sphx_glr_integration_with_error_002.png
          :alt: compare manual vs. automatic
          :class: sphx-glr-multi-img

    *

      .. image:: /auto_examples/images/sphx_glr_integration_with_error_003.png
          :alt: signal Energy
          :class: sphx-glr-multi-img

    *

      .. image:: /auto_examples/images/sphx_glr_integration_with_error_004.png
          :alt: raw data
          :class: sphx-glr-multi-img

    *

      .. image:: /auto_examples/images/sphx_glr_integration_with_error_005.png
          :alt: real part of raw data
          :class: sphx-glr-multi-img


.. rst-class:: sphx-glr-script-out

 Out:

 .. code-block:: none

    C:\Users\Alex Guinness\pyspecdata.0.log appears to be locked or otherwise inaccessible: I'm going to explore other options for fileno
    logging output to C:\Users\Alex Guinness\pyspecdata.2.log
    FWHM IS 171.17117945945947
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u03c3' in position 158: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 277, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 333, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 437, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 381, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 862, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 784, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 591, in execute_code_block
        mem_body, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 205, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 516, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\Alex Guinness\gitstuff\proc_scripts\examples\integration_with_error.py", line 111, in <module>
        fl.plot(
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2025, in plot
        retval = plot(*tuple((firstarg,)+args[1:]),**kwargs)#just a placeholder for now, will later keep units + such
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2662, in plot
        logger.debug(strm("here are the kwargs",kwargs))
    Message: "here are the kwargs {'capsize': 6, 'label': 'manual bounds (programmed σ)\\n$  60\\\\rightarrow 140$', 'alpha': 0.5, 'yerr': None, 'linestyle': '', 'marker': '.'}"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u03c3' in position 158: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 277, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 333, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 437, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 381, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 862, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 784, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 591, in execute_code_block
        mem_body, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 205, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 516, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\Alex Guinness\gitstuff\proc_scripts\examples\integration_with_error.py", line 111, in <module>
        fl.plot(
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2025, in plot
        retval = plot(*tuple((firstarg,)+args[1:]),**kwargs)#just a placeholder for now, will later keep units + such
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2662, in plot
        logger.debug(strm("here are the kwargs",kwargs))
    Message: "here are the kwargs {'capsize': 6, 'label': 'manual bounds (programmed σ)\\n$  60\\\\rightarrow 140$', 'alpha': 0.5, 'yerr': None, 'linestyle': '', 'marker': '.'}"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u03c3' in position 158: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 277, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 333, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 437, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 381, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 862, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 784, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 591, in execute_code_block
        mem_body, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 205, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 516, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\Alex Guinness\gitstuff\proc_scripts\examples\integration_with_error.py", line 111, in <module>
        fl.plot(
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2025, in plot
        retval = plot(*tuple((firstarg,)+args[1:]),**kwargs)#just a placeholder for now, will later keep units + such
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2662, in plot
        logger.debug(strm("here are the kwargs",kwargs))
    Message: "here are the kwargs {'capsize': 6, 'label': 'manual bounds (programmed σ)\\n$  60\\\\rightarrow 140$', 'alpha': 0.5, 'yerr': None, 'linestyle': '', 'marker': '.'}"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u03c3' in position 159: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 277, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 333, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 437, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 381, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 862, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 784, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 591, in execute_code_block
        mem_body, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 205, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 516, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\Alex Guinness\gitstuff\proc_scripts\examples\integration_with_error.py", line 119, in <module>
        fl.plot(manual_bounds,
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2025, in plot
        retval = plot(*tuple((firstarg,)+args[1:]),**kwargs)#just a placeholder for now, will later keep units + such
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2662, in plot
        logger.debug(strm("here are the kwargs",kwargs))
    Message: "here are the kwargs {'capsize': 6, 'label': 'manual bounds (inactive CT σ)\\n$  60\\\\rightarrow 140$', 'alpha': 0.5, 'yerr': None, 'linestyle': '', 'marker': '.'}"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u03c3' in position 159: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 277, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 333, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 437, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 381, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 862, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 784, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 591, in execute_code_block
        mem_body, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 205, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 516, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\Alex Guinness\gitstuff\proc_scripts\examples\integration_with_error.py", line 119, in <module>
        fl.plot(manual_bounds,
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2025, in plot
        retval = plot(*tuple((firstarg,)+args[1:]),**kwargs)#just a placeholder for now, will later keep units + such
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2662, in plot
        logger.debug(strm("here are the kwargs",kwargs))
    Message: "here are the kwargs {'capsize': 6, 'label': 'manual bounds (inactive CT σ)\\n$  60\\\\rightarrow 140$', 'alpha': 0.5, 'yerr': None, 'linestyle': '', 'marker': '.'}"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u03c3' in position 159: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 277, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 333, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 437, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 381, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 862, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 784, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 591, in execute_code_block
        mem_body, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 205, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 516, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\Alex Guinness\gitstuff\proc_scripts\examples\integration_with_error.py", line 119, in <module>
        fl.plot(manual_bounds,
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2025, in plot
        retval = plot(*tuple((firstarg,)+args[1:]),**kwargs)#just a placeholder for now, will later keep units + such
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2662, in plot
        logger.debug(strm("here are the kwargs",kwargs))
    Message: "here are the kwargs {'capsize': 6, 'label': 'manual bounds (inactive CT σ)\\n$  60\\\\rightarrow 140$', 'alpha': 0.5, 'yerr': None, 'linestyle': '', 'marker': '.'}"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u03c3' in position 156: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 277, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 333, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 437, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 381, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 862, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 784, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 591, in execute_code_block
        mem_body, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 205, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 516, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\Alex Guinness\gitstuff\proc_scripts\examples\integration_with_error.py", line 111, in <module>
        fl.plot(
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2025, in plot
        retval = plot(*tuple((firstarg,)+args[1:]),**kwargs)#just a placeholder for now, will later keep units + such
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2662, in plot
        logger.debug(strm("here are the kwargs",kwargs))
    Message: "here are the kwargs {'capsize': 6, 'label': 'auto bounds (programmed σ)\\n$-21.9785\\\\rightarrow221.783$', 'alpha': 0.5, 'yerr': None, 'linestyle': '', 'marker': '.'}"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u03c3' in position 156: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 277, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 333, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 437, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 381, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 862, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 784, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 591, in execute_code_block
        mem_body, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 205, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 516, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\Alex Guinness\gitstuff\proc_scripts\examples\integration_with_error.py", line 111, in <module>
        fl.plot(
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2025, in plot
        retval = plot(*tuple((firstarg,)+args[1:]),**kwargs)#just a placeholder for now, will later keep units + such
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2662, in plot
        logger.debug(strm("here are the kwargs",kwargs))
    Message: "here are the kwargs {'capsize': 6, 'label': 'auto bounds (programmed σ)\\n$-21.9785\\\\rightarrow221.783$', 'alpha': 0.5, 'yerr': None, 'linestyle': '', 'marker': '.'}"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u03c3' in position 156: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 277, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 333, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 437, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 381, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 862, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 784, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 591, in execute_code_block
        mem_body, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 205, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 516, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\Alex Guinness\gitstuff\proc_scripts\examples\integration_with_error.py", line 111, in <module>
        fl.plot(
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2025, in plot
        retval = plot(*tuple((firstarg,)+args[1:]),**kwargs)#just a placeholder for now, will later keep units + such
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2662, in plot
        logger.debug(strm("here are the kwargs",kwargs))
    Message: "here are the kwargs {'capsize': 6, 'label': 'auto bounds (programmed σ)\\n$-21.9785\\\\rightarrow221.783$', 'alpha': 0.5, 'yerr': None, 'linestyle': '', 'marker': '.'}"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u03c3' in position 157: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 277, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 333, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 437, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 381, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 862, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 784, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 591, in execute_code_block
        mem_body, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 205, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 516, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\Alex Guinness\gitstuff\proc_scripts\examples\integration_with_error.py", line 119, in <module>
        fl.plot(manual_bounds,
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2025, in plot
        retval = plot(*tuple((firstarg,)+args[1:]),**kwargs)#just a placeholder for now, will later keep units + such
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2662, in plot
        logger.debug(strm("here are the kwargs",kwargs))
    Message: "here are the kwargs {'capsize': 6, 'label': 'auto bounds (inactive CT σ)\\n$-21.9785\\\\rightarrow221.783$', 'alpha': 0.5, 'yerr': None, 'linestyle': '', 'marker': '.'}"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u03c3' in position 157: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 277, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 333, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 437, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 381, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 862, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 784, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 591, in execute_code_block
        mem_body, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 205, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 516, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\Alex Guinness\gitstuff\proc_scripts\examples\integration_with_error.py", line 119, in <module>
        fl.plot(manual_bounds,
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2025, in plot
        retval = plot(*tuple((firstarg,)+args[1:]),**kwargs)#just a placeholder for now, will later keep units + such
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2662, in plot
        logger.debug(strm("here are the kwargs",kwargs))
    Message: "here are the kwargs {'capsize': 6, 'label': 'auto bounds (inactive CT σ)\\n$-21.9785\\\\rightarrow221.783$', 'alpha': 0.5, 'yerr': None, 'linestyle': '', 'marker': '.'}"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u03c3' in position 157: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 277, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 333, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 437, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 381, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 862, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 784, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 591, in execute_code_block
        mem_body, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 205, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 516, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\Alex Guinness\gitstuff\proc_scripts\examples\integration_with_error.py", line 119, in <module>
        fl.plot(manual_bounds,
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2025, in plot
        retval = plot(*tuple((firstarg,)+args[1:]),**kwargs)#just a placeholder for now, will later keep units + such
      File "c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py", line 2662, in plot
        logger.debug(strm("here are the kwargs",kwargs))
    Message: "here are the kwargs {'capsize': 6, 'label': 'auto bounds (inactive CT σ)\\n$-21.9785\\\\rightarrow221.783$', 'alpha': 0.5, 'yerr': None, 'linestyle': '', 'marker': '.'}"
    Arguments: ()
    c:\users\alex guinness\gitstuff\pyspecdata\pyspecdata\core.py:2174: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
      plt.gcf().tight_layout()






|

.. code-block:: default

    from pylab import *
    from pyspecdata import *
    from pyspecProcScripts import integrate_limits, integral_w_errors
    from numpy.random import seed

    # sphinx_gallery_thumbnail_number = 2

    seed(2021)  # so the same random result is generated every time -- 2021 is meaningless
    init_logging(level="debug")
    fl = figlist_var()
    t2 = nddata(r_[0:1:1024j], "t2")
    vd = nddata(r_[0:1:40j], "vd")
    ph1 = nddata(r_[0, 2] / 4.0, "ph1")
    ph2 = nddata(r_[0:4] / 4.0, "ph2")
    signal_pathway = {"ph1": 0, "ph2": 1}
    excluded_pathways = [(0, 0), (0, 3)]
    manual_slice = (60,140) # manually chosen integration bounds
    # this generates fake data w/ a T₂ of 0.2s
    # amplitude of 21, just to pick a random amplitude
    # offset of 300 Hz, FWHM 10 Hz
    data = 21*(1 - 2*exp(-vd / 0.2))*exp(+1j*2*pi*100*t2 - t2*10*pi)
    data *= exp(signal_pathway["ph1"]*1j*2*pi*ph1)
    data *= exp(signal_pathway["ph2"]*1j*2*pi*ph2)
    data["t2":0] *= 0.5
    fake_data_noise_std = 2.0
    data.add_noise(fake_data_noise_std)
    data.reorder(["ph1", "ph2", "vd"])
    # at this point, the fake data has been generated
    data.ft(["ph1", "ph2"])
    fl.next("what does a usual error bar look like?")
    just_noise = nddata(r_[0:1:50j], "t")
    just_noise.data *= 0
    just_noise.add_noise(fake_data_noise_std)
    just_noise.set_error(fake_data_noise_std)
    fl.plot(just_noise, ".", capsize=6)
    # {{{ usually, we don't use a unitary FT -- this makes it unitary
    data /= 0.5 * 0.25  # the dt in the integral for both dims
    data /= sqrt(ndshape(data)["ph1"] * ndshape(data)["ph2"])  # normalization
    # }}}
    data.ft("t2", shift=True)
    dt = data.get_ft_prop("t2","dt")
    # {{{ vector-normalize the FT
    data /= sqrt(ndshape(data)['t2']) * dt
    # }}}
    # {{{ First, run the code that automatically chooses integration bounds
    # and also assigns error
    fl.next("compare manual vs. automatic", legend=True)
    error_pathway = (set(((j, k) for j in range(ndshape(data)['ph1']) for k in range(ndshape(data)['ph2'])))
            - set(excluded_pathways)
            - set([(signal_pathway['ph1'], signal_pathway['ph2'])])
    )
    error_pathway = [{'ph1':j, 'ph2':k} for j,k in error_pathway]
    s_int, returned_frq_slice = integral_w_errors(data, signal_pathway, error_pathway,
            fl=fl, return_frq_slice=True)
    fl.plot(s_int, ".", label="fully auto: real", capsize=6)
    fl.plot(s_int.imag, ".", label="fully auto: imaginary", capsize=6)
    # }}}
    logger.debug(strm("check the std after FT", std(data["ph1", 0]["ph2", 0].data.real)))
    # the sqrt on the next line accounts for the var(real)+var(imag)
    fl.next("raw data")
    fl.image(data, alpha=0.5)
    fl.next("real part of raw data")
    fl.image(data.real, alpha=0.5)
    fl.next("compare manual vs. automatic")
    # run a controlled comparison between manually chosen integration bounds and
    # compare against automatically generated
    # as noted in issue #44 , manually chosen bounds underperform
    for bounds,thislabel in [
        (manual_slice,'manual bounds'),  # leave this as a loop so user can experiment with different bounds
        (tuple(returned_frq_slice),'auto bounds'),  # leave this as a loop so user can experiment with different bounds
    ]:
        manual_bounds = data["ph1", 0]["ph2", 1]["t2":bounds]
        assert manual_bounds.get_ft_prop('t2')
        std_from_00 = (
            data["ph1", 0]["ph2", 0]["t2":bounds]
            .C.run(lambda x: abs(x)**2/2)
            .mean_all_but(["t2","vd"])
            .mean("t2")
            .run(sqrt)
        )
        logger.debug(
            strm(
                "here is the std calculated from an off pathway",
                std_from_00,
                "does it match",
                fake_data_noise_std,
                "?",
            )
        )
        N = ndshape(manual_bounds)["t2"]
        df = manual_bounds.get_ft_prop('t2','df')
        logger.debug(
            strm(ndshape(manual_bounds), "df is", df, "N is", N, "N*df is", N * df)
        )
        manual_bounds.integrate("t2")
        # N terms that have variance given by fake_data_noise_std**2 each multiplied by df
        # the 2 has to do w/ real/imag/abs -- see check_integration_error
        propagated_variance = N * df ** 2 * fake_data_noise_std ** 2
        propagated_variance_from_inactive = N * df ** 2 * std_from_00 ** 2
        logger.debug(
            strm("manually calculated integral error is", sqrt(propagated_variance))
        )
        manual_bounds.set_error(sqrt(propagated_variance))
        fl.plot(
            manual_bounds,
            ".",
            capsize=6,
            label="%s (programmed σ)\n$%4g\\rightarrow%4g$" % ((thislabel,)+bounds),
            alpha=0.5,
        )
        manual_bounds.set_error(sqrt(propagated_variance_from_inactive.data))
        fl.plot(manual_bounds,
                '.',capsize=6,
                label="%s (inactive CT σ)\n$%4g\\rightarrow%4g$" % ((thislabel,)+bounds),
                alpha=0.5)
    fl.show()


.. rst-class:: sphx-glr-timing

   **Total running time of the script:** ( 0 minutes  1.406 seconds)


.. _sphx_glr_download_auto_examples_integration_with_error.py:


.. only :: html

 .. container:: sphx-glr-footer
    :class: sphx-glr-footer-example



  .. container:: sphx-glr-download sphx-glr-download-python

     :download:`Download Python source code: integration_with_error.py <integration_with_error.py>`



  .. container:: sphx-glr-download sphx-glr-download-jupyter

     :download:`Download Jupyter notebook: integration_with_error.ipynb <integration_with_error.ipynb>`


.. only:: html

 .. rst-class:: sphx-glr-signature

    `Gallery generated by Sphinx-Gallery <https://sphinx-gallery.github.io>`_
